# Generated by Django 2.2.3 on 2019-08-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boilr', '0002_auto_20190811_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='humidity',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='temperature',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
